FROM ubuntu

WORKDIR /tmp
ENV PYTHON=python2.7

RUN apt-get update && apt-get install -y build-essential wget git python2.7 bzip2 libkrb5-dev
RUN wget nodejs.org/dist/v0.10.48/node-v0.10.48-linux-x64.tar.gz
RUN tar -C /usr/local --strip-components 1 -xzf node-v0.10.48-linux-x64.tar.gz

ADD ./package.json /app/
WORKDIR /app

RUN npm install -g bower
RUN npm install

ADD ./ /app

RUN bower install --allow-root

CMD npm start
